Repository CanHub/Android-Image-Cropper, pull requests merged in 2021-01, with the labels that each got.

#22 Add jitpack support for publishing
  README.md
  build.gradle
  cropper/build.gradle
  cropper/publish.gradle
Labels: documentation

#25 Migrated Deprecated AsyncTask to Kotlin Coroutines
  CHANGELOG.md
  README.md
  build.gradle
  cropper/build.gradle
  cropper/src/main/java/com/canhub/cropper/BitmapCroppingWorkerJob.kt
  cropper/src/main/java/com/canhub/cropper/BitmapCroppingWorkerTask.java
  cropper/src/main/java/com/canhub/cropper/BitmapLoadingWorkerJob.kt
  cropper/src/main/java/com/canhub/cropper/BitmapLoadingWorkerTask.java
  cropper/src/main/java/com/canhub/cropper/BitmapUtils.java
  cropper/src/main/java/com/canhub/cropper/CropImage.java
  cropper/src/main/java/com/canhub/cropper/CropImageActivity.kt
  cropper/src/main/java/com/canhub/cropper/CropImageView.java
  cropper/src/main/java/com/canhub/cropper/CropOverlayView.java
  cropper/src/main/java/com/canhub/cropper/CropWindowHandler.java
  cropper/src/main/java/com/canhub/cropper/CropWindowMoveHandler.java
  cropper/src/main/java/com/canhub/cropper/common/CommonVersionCheck.kt
  quick-start/build.gradle
  sample/build.gradle
  test/build.gradle
Labels: enhancement

#27 Fix: File is not a picture (on Android 10 or above)
  CHANGELOG.md
  cropper/src/main/java/com/canhub/cropper/CropImage.java
Labels: bug

#43 Update README.md
  README.md
Labels: documentation

#47 Refactor/crop image options to kotlin
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CHANGELOG.md
  build.gradle
  cropper/build.gradle
  cropper/src/main/java/com/canhub/cropper/BitmapCroppingWorkerJob.kt
  cropper/src/main/java/com/canhub/cropper/BitmapUtils.java
  cropper/src/main/java/com/canhub/cropper/CropImageOptions.java
  cropper/src/main/java/com/canhub/cropper/CropImageOptions.kt
  cropper/src/main/java/com/canhub/cropper/CropImageView.java
  gradle/gradle/wrapper/gradle-wrapper.jar
  gradle/gradle/wrapper/gradle-wrapper.properties
  quick-start/build.gradle
  quick-start/src/main/AndroidManifest.xml
  quick-start/src/main/java/com/canhub/cropper/quick_start/MainActivity.kt
  quick-start/src/main/res/drawable-xhdpi/placeholder.png
  quick-start/src/main/res/drawable/ic_launcher.xml
  quick-start/src/main/res/layout/activity_main.xml
  quick-start/src/main/res/values/dimens.xml
  quick-start/src/main/res/values/strings.xml
  quick-start/src/main/res/values/styles.xml
  sample/build.gradle
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/canhub/cropper/sample/CropDemoPreset.java
  sample/src/main/java/com/canhub/cropper/sample/CropDemoPreset.kt
  sample/src/main/java/com/canhub/cropper/sample/CropImageViewOptions.java
  sample/src/main/java/com/canhub/cropper/sample/CropImageViewOptions.kt
  sample/src/main/java/com/canhub/cropper/sample/CropResultActivity.java
  sample/src/main/java/com/canhub/cropper/sample/CropResultActivity.kt
  sample/src/main/java/com/canhub/cropper/sample/MainActivity.java
  sample/src/main/java/com/canhub/cropper/sample/MainActivity.kt
  sample/src/main/java/com/canhub/cropper/sample/MainFragment.java
  sample/src/main/java/com/canhub/cropper/sample/MainFragment.kt
  settings.gradle
  test/.gitignore
  test/build.gradle
  test/src/main/AndroidManifest.xml
  test/src/main/java/com/canhub/cropper/test/MainActivity.kt
  test/src/main/res/drawable/ic_launcher.xml
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/values/colors.xml
  test/src/main/res/values/strings.xml
  test/src/main/res/values/styles.xml
  versions.gradle
Labels: bug, enhancement
